### PR TITLE
Support Hide/Shine without animation

### PR DESCRIPTION
**Pull request by PauliusVindzigelskis**
Also, had to update demo project to run on latest Xcode

### CODE REVIEW

**Comment by PauliusVindzigelskis** [comment]
Can You kick new Cocoapod version?

**Comment by zipme** [comment]
Done.

**Comment by PauliusVindzigelskis** [comment]
I would’ve created version like 0.2.0 or 1.0.0 as API changed. 
Third version part is commonly used for bug fixes

**Comment by zipme** [comment]
True, we should follow semantic versioning, let me see if I can change it or otherwise I would just release another version

**Comment by PauliusVindzigelskis** [comment]
pod trunk delete {podname} {version} 

might help to remove latest version

**Comment by zipme** [comment]
Done.

**Comment by PauliusVindzigelskis** [comment]
All looks good. Thanks!

**Pull request merged**
